# 异常 (try, catch, throw)
```c
try {
    z = hmean(x,y);
} catch (const char * s) {
    std::cout << s << std::endl;
    ...
}
   
double hmean(double a, double b) {
    if (a == -b) {
        throw "ban hmean() arguments: a = -b not allowed";
    }
    return 2.0 * a * b / (a + b);
}
```

c++异常的主要目的是为了设计容错程序提供语言级支持，异常使得在程序设计中包含错误处理功能更容易，以免事后采取更严格的错误处理方式。

```c
#include <exception>
class bad_hmean : public std::exception {
public:
    const char * what() {
        return "bad argument to hmean()";
    }
    ...
};

class bad_gmean : public std::exception {
public:
    const char * what() {
        return "bad arguments to gmean()";
    }
    ...
}
```

标准库中定义了几个异常类: domain_error, invalid_argument, length_error, out_of_bounds, runtime_error等等

```c
try {...}
catch(out_of_bounds & oe) {...}
catch(logic_error & oe) {...}
catch(exception & oe) {...}
```

对于处理使用new时可能出现的内存分配问题。你可以选择让new返回一个空指针，或者让new引发bad_alloc异常。
